<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit7f28edf673ef536009701bb91a866dc7
{
    public static $prefixLengthsPsr4 = array (
        'P' =>
        array (
            'Psr\\Log\\' => 8,
        ),
        'L' =>
        array (
            'Laminas\\Escaper\\' => 16,
        ),
        'C' =>
        array (
            'Config\\' => 7,
            'CodeIgniter\\' => 12,
        ),
        'A' =>
        array (
            'App\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Psr\\Log\\' =>
        array (
            0 => __DIR__ . '/..' . '/psr/log/src',
        ),
        'Laminas\\Escaper\\' =>
        array (
            0 => __DIR__ . '/..' . '/laminas/laminas-escaper/src',
        ),
        'Config\\' =>
        array (
            0 => __DIR__ . '/../..' . '/app/Config',
        ),
        'CodeIgniter\\' =>
        array (
            0 => __DIR__ . '/..' . '/codeigniter4/framework/system',
        ),
        'App\\' =>
        array (
            0 => __DIR__ . '/../..' . '/app',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit7f28edf673ef536009701bb91a866dc7::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit7f28edf673ef536009701bb91a866dc7::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit7f28edf673ef536009701bb91a866dc7::$classMap;

        }, null, ClassLoader::class);
    }
}
